worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;

    log_format gateway_edge '$remote_addr - [$time_local] "$request" '
                             'status=$status bytes=$body_bytes_sent '
                             'rt=$request_time upstream_rt=$upstream_response_time '
                             'referrer="$http_referer" ua="$http_user_agent"';

    access_log /var/log/nginx/access.log gateway_edge;
    error_log  /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/*.conf;
}
